[package]
name = "qtwidgets"
version = "0.1.0"
authors = ["egitop <egitop@abc.xyz>"]
edition = "2018"

[dependencies]
qtrt = { path = "../qtrt" }
qtcore = { path = "../qtcore" }
qtgui = { path = "../qtgui" }

